### ISSUE TITLE
Validated fields not supporting Unicode?

### ISSUE THREAD

**Issue by OverflowCat** [zanechua/comment-worker#2]
When using CJK characters in `fields` with `x-www-form-urlencoded`, a 500 Internal Server Error occurs.

I didn't put `slug` in `options`, so it appears it isn't validated, allowing me to use CJK characters there.

![image](https://github.com/zanechua/comment-worker/assets/20166026/8e2c4545-f2d9-4627-9087-94f96604841a)

![image](https://github.com/zanechua/comment-worker/assets/20166026/e21615a1-6d87-4125-8d91-df78cf5f927b)

**Comment by zanechua** [comment]
@OverflowCat there's two distinct issues here right?

1. Support for Unicode so we can get CJK
2. Validation not happening for something?

EDIT:

Please also provide the body in text format so I can validate this.

EDIT 2: 

Please also provide your `staticman.yml` configuration or a repro project.

**Comment by OverflowCat** [comment]
Nope, I mean validation may cause such a bug. I found that Unicode cannot be used in `fields`, but it can be in `options`. Additionally, this issue persists when submitting via `application/json`, so it's not related to the submission method used.

Body:

```json
{
  "fields": {
    "name": "hello世界",
    "email": "someone@example.com",
    "message": "Hello"
  },
  "options": {
    "slug": "test/page"
  }
}
```

Remove `世界` in the json and it should work.

Config file:

```yaml
comments:
  allowedFields: ["name", "email", "url", "message", "twitter", "activitypub"]

  branch: "src"

  commitMessage: "comment: add staticman data"

  filename: "entry{@timestamp}"

  format: "yaml"

  generatedFields:
    date:
      type: date
      options:
        format: "timestamp-seconds"

  moderation: true

  name: "my-site.com"

  path: "comments/{options.slug}"

  requiredFields: ["name", "email", "message"]

  transforms:
    email: md5

```
